# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/113phu5bA8F3og-bmwjOoGGNURe7q_PZh
"""



# Drop the 'Id' column and separate features and labels
X = data.drop(columns=['Id', 'Species'])  # Features
Y = data['Species']  # Labels

import pandas as pd

path="/content/drive/MyDrive/Dataset/Iris.csv"
df=pd.read_csv(path)
df.head(5)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load dataset from CSV file
data = pd.read_csv(

# Display first few rows of data
print(data.head())

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load dataset from CSV file
data = pd.read_csv("/content/drive/MyDrive/Dataset/Iris.csv")

# Display first few rows of data
print(data.head())

# Drop the 'Id' column and prepare X and Y
X = data.drop(columns=['Id', 'Species'])  # Features: Sepal and Petal dimensions
Y = data['Species']  # Target: Flower species

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

# Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=200)
model.fit(X_train, Y_train)

# Make predictions on the test set
Y_pred = model.predict(X_test)

accuracy = accuracy_score(Y_test, Y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

!apt-get install git

!git clone https://github.com/stevejohns123/repo_name.git

